package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/arun-skg/envdoctor/go/internal/scanner"
)

func TestInitAndFix(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, ".env"), "DB_URL=postgres://x\n")
	writeFile(t, filepath.Join(dir, "main.go"), "package main\nimport \"os\"\nfunc main(){ os.Getenv(\"PORT\") }\n")

	example := filepath.Join(dir, ".env.example")
	envdoc := filepath.Join(dir, "ENVIRONMENT.md")
	wantExample := "# Generated by envdoctor. Fill in values; do not commit secrets.\nDB_URL=\nPORT=\n"

	// init creates both files.
	if code := run([]string{"init", "--dir", dir}); code != 0 {
		t.Fatalf("init exit = %d", code)
	}
	if got := readFile(t, example); got != wantExample {
		t.Fatalf(".env.example = %q, want %q", got, wantExample)
	}
	md := readFile(t, envdoc)
	if !containsAll(md, "| DB_URL | yes | no |", "| PORT | no | yes |") {
		t.Fatalf("ENVIRONMENT.md wrong: %q", md)
	}
	if strings.Contains(readFile(t, example), "postgres") || strings.Contains(md, "postgres") {
		t.Fatal("value leaked into generated docs")
	}

	// init again without --force skips (files unchanged).
	writeFile(t, example, "SENTINEL")
	if code := run([]string{"init", "--dir", dir}); code != 0 {
		t.Fatalf("second init exit = %d", code)
	}
	if got := readFile(t, example); got != "SENTINEL" {
		t.Fatalf("init without --force should skip, got %q", got)
	}

	// --force rewrites.
	if code := run([]string{"init", "--dir", dir, "--force"}); code != 0 {
		t.Fatalf("forced init exit = %d", code)
	}
	if got := readFile(t, example); got != wantExample {
		t.Fatalf("forced init should rewrite, got %q", got)
	}

	// fix always rewrites.
	writeFile(t, example, "STALE")
	if code := run([]string{"fix", "--dir", dir}); code != 0 {
		t.Fatalf("fix exit = %d", code)
	}
	if got := readFile(t, example); got != wantExample {
		t.Fatalf("fix should rewrite, got %q", got)
	}
}

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}

func containsAll(s string, subs ...string) bool {
	for _, sub := range subs {
		if !strings.Contains(s, sub) {
			return false
		}
	}
	return true
}

func TestToJSONShape(t *testing.T) {
	findings := []scanner.Finding{
		{Rule: "unused", Severity: "warning", Name: "FOO",
			Message: "defined but never referenced in source",
			Origin:  scanner.Origin{File: ".env", Line: 3}},
		{Rule: "typo", Severity: "warning", Name: "BAR",
			Message: "x", Origin: scanner.Origin{}},
	}
	data, err := json.Marshal(toJSON(findings))
	if err != nil {
		t.Fatal(err)
	}
	var arr []map[string]interface{}
	if err := json.Unmarshal(data, &arr); err != nil {
		t.Fatal(err)
	}
	if len(arr) != 2 {
		t.Fatalf("expected 2 objects, got %d", len(arr))
	}
	wantKeys := []string{"rule", "severity", "name", "message", "file", "line"}
	for _, obj := range arr {
		if len(obj) != len(wantKeys) {
			t.Fatalf("unexpected keys: %v", obj)
		}
		for _, k := range wantKeys {
			if _, ok := obj[k]; !ok {
				t.Fatalf("missing key %q in %v", k, obj)
			}
		}
	}
	// First finding has a real file; second has null file/line.
	if arr[0]["file"] != ".env" {
		t.Fatalf("expected file .env, got %v", arr[0]["file"])
	}
	if arr[1]["file"] != nil || arr[1]["line"] != nil {
		t.Fatal("expected null file/line for empty origin")
	}
}
