import { isSecretName } from "../models/environment-variable.js";
import type { ProjectModel } from "../models/project-model.js";

/**
 * Generate a deterministic `.env.example` for a project.
 *
 * Security rules:
 * - Secret-like variables always get a blank value.
 * - Non-secret values are copied ONLY from the base `.env` (development) file.
 *   Nothing is ever copied from `.env.production`, `.env.local`, or any other
 *   environment, and no secret value is ever written.
 */
export function generateEnvExample(model: ProjectModel): string {
  // Names the app actually consumes (source + compose + actions).
  const used = new Set<string>();
  for (const file of [...model.sourceFiles, ...model.composeFiles, ...model.actionFiles]) {
    for (const v of file.variables) used.add(v.name);
    for (const v of file.usages) used.add(v.name);
  }

  // Names defined in environment files (including .env.example).
  const defined = new Set<string>();
  for (const file of model.envFiles) {
    for (const v of file.variables) defined.add(v.name);
  }

  const required = new Set([...used]);
  const optional = new Set([...defined].filter((n) => !required.has(n)));

  const lines: string[] = [];
  lines.push("# .env.example");
  lines.push("# Generated by envdoctor. Copy to .env and fill in real values.");
  lines.push("# Secret values are intentionally left blank — never commit secrets.");
  lines.push("");

  const valueFor = (name: string): string => {
    if (isSecretName(name)) return "";
    const base = model.envFiles.find(
      (file) =>
        file.environment === "development" &&
        file.variables.some((v) => v.name === name && (v.value ?? "") !== ""),
    );
    const def = base?.variables.find((v) => v.name === name);
    return def?.value ?? "";
  };

  if (required.size > 0) {
    lines.push("# Required by the application");
    for (const name of sorted(required)) {
      lines.push(`${name}=${valueFor(name)}`);
    }
    lines.push("");
  }

  if (optional.size > 0) {
    lines.push("# Optional / configuration knobs");
    for (const name of sorted(optional)) {
      lines.push(`${name}=${valueFor(name)}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

function sorted(names: Set<string>): string[] {
  return Array.from(names).sort((a, b) => a.localeCompare(b));
}
