import type { ProjectModel } from "../models/project-model.js";

/**
 * Generate a TypeScript ambient declaration for NodeJS.ProcessEnv based on all
 * known environment variables.
 *
 * Values are never emitted — only names and inferred types as JSDoc comments.
 */
export function generateEnvTypes(model: ProjectModel): string {
  const names = new Map<
    string,
    { type: string; isSecret: boolean; inferredType?: string }
  >();

  for (const file of model.allFiles) {
    for (const v of file.variables) {
      const existing = names.get(v.name);
      if (!existing) {
        names.set(v.name, {
          type: "string",
          isSecret: v.isSecret,
          inferredType: v.type === "unknown" ? undefined : v.type,
        });
      } else if (v.type !== "unknown" && !existing.inferredType) {
        existing.inferredType = v.type;
      }
    }
    for (const v of file.usages) {
      if (!names.has(v.name)) {
        names.set(v.name, { type: "string", isSecret: v.isSecret });
      }
    }
  }

  const lines: string[] = [];
  lines.push("// Generated by envdoctor. Do not edit manually.");
  lines.push("// This file declares types for process.env variables.");
  lines.push("// Secret values are never included.");
  lines.push("");
  lines.push("declare global {");
  lines.push("  namespace NodeJS {");
  lines.push("    interface ProcessEnv {");

  const sortedNames = Array.from(names.keys()).sort((a, b) => a.localeCompare(b));
  for (const name of sortedNames) {
    const meta = names.get(name)!;
    const docParts: string[] = [];
    if (meta.isSecret) docParts.push("secret");
    if (meta.inferredType) docParts.push(`inferred type: ${meta.inferredType}`);
    if (docParts.length > 0) {
      lines.push(`      /** ${docParts.join(" · ")} */`);
    }
    lines.push(`      ${name}: string;`);
  }

  lines.push("    }");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("export {};");
  lines.push("");

  return lines.join("\n");
}
