import type { ProjectModel } from "../models/project-model.js";
import type { VariableType } from "../models/variable-type.js";

/**
 * Generate `ENVIRONMENT.md` — a human-readable reference for a project's
 * environment variables. Names only; no values ever appear.
 */
export function generateEnvironmentDoc(model: ProjectModel): string {
  const names = collectNames(model);

  const lines: string[] = [];
  lines.push("# Environment Variables");
  lines.push("");
  lines.push(
    "> Generated by envdoctor. Do not edit by hand — run `envdoctor fix` to regenerate.",
  );
  lines.push("");

  // ---- Overview table ----
  lines.push("## Overview");
  lines.push("");
  lines.push("| Variable | Type | Defined in | Used in source | Secret |");
  lines.push("| --- | --- | --- | --- | --- |");
  for (const name of names.sorted) {
    const info = names.info.get(name) ?? { environments: [], usedInSource: false, isSecret: false };
    const type = info.type ?? "unknown";
    const envs = info.environments.length > 0 ? info.environments.join(", ") : "—";
    const source = info.usedInSource ? "✓" : "—";
    const secret = info.isSecret ? "✓" : "—";
    lines.push(`| ${name} | ${type} | ${envs} | ${source} | ${secret} |`);
  }
  lines.push("");

  // ---- Missing ----
  if (names.missing.length > 0) {
    lines.push("## Referenced but not defined");
    lines.push("");
    lines.push(
      "These variables are expected somewhere in the project but are not defined in any environment file:",
    );
    lines.push("");
    for (const name of names.missing) {
      lines.push(`- \`${name}\``);
    }
    lines.push("");
  }

  // ---- Per-environment sections ----
  lines.push("## Environments");
  lines.push("");
  const envLabels = distinctEnvLabels(model);
  if (envLabels.length === 0) {
    lines.push("No environment files found.");
    lines.push("");
  } else {
    for (const label of envLabels) {
      const files = model.envFiles
        .filter((file) => file.environment === label)
        .map((file) => `\`${file.filePath}\``);
      lines.push(`### ${label}`);
      lines.push("");
      lines.push(files.length > 0 ? `Defined in ${files.join(", ")}.` : "");
      const vars = names.sorted.filter(
        (name) => (names.info.get(name)?.environments.length ?? 0) > 0 && names.info.get(name)?.environments.includes(label),
      );
      for (const name of vars) lines.push(`- ${name}`);
      lines.push("");
    }
  }

  return lines.join("\n");
}

interface NameInfo {
  type?: VariableType;
  environments: string[];
  usedInSource: boolean;
  isSecret: boolean;
}

interface NamesIndex {
  sorted: string[];
  info: Map<string, NameInfo>;
  missing: string[];
}

function collectNames(model: ProjectModel): NamesIndex {
  const names = new Set<string>();
  const info = new Map<string, NameInfo>();
  const exampleNames = new Set<string>();

  // Definitions and usages from environment files. `.env.example` is
  // documentation — it does not count as a real environment.
  for (const file of model.envFiles) {
    for (const v of file.variables) {
      names.add(v.name);
      if (file.environment === "example") {
        exampleNames.add(v.name);
        continue;
      }
      const entry = info.get(v.name) ?? { environments: [], usedInSource: false, isSecret: v.isSecret };
      if (file.environment && !entry.environments.includes(file.environment)) {
        entry.environments.push(file.environment);
      }
      if (entry.type === undefined && v.type !== "unknown") entry.type = v.type;
      entry.isSecret ||= v.isSecret;
      info.set(v.name, entry);
    }
  }

  // Source usages.
  const sourceUsed = new Set<string>();
  for (const file of model.sourceFiles) {
    for (const v of file.usages) {
      names.add(v.name);
      sourceUsed.add(v.name);
    }
  }

  // Compose definitions and usages. GitHub Actions is intentionally excluded:
  // workflow `env:` keys are internal, and secrets/vars live in repo settings
  // (tracked by the separate actions checklist generator).
  const composeRefs = new Set<string>();
  for (const file of model.composeFiles) {
    for (const v of file.variables) {
      names.add(v.name);
      composeRefs.add(v.name);
      const entry = info.get(v.name) ?? { environments: [], usedInSource: false, isSecret: v.isSecret };
      entry.isSecret ||= v.isSecret;
      info.set(v.name, entry);
    }
    for (const v of file.usages) {
      names.add(v.name);
      composeRefs.add(v.name);
    }
  }

  for (const name of sourceUsed) {
    const entry = info.get(name) ?? { environments: [], usedInSource: false, isSecret: false };
    entry.usedInSource = true;
    info.set(name, entry);
  }

  // Referenced but not defined in any real environment file. This mirrors the
  // audit's missing + undefined-in-source semantics: source usage, compose
  // reference, or `.env.example` documentation without a runtime definition.
  const missing = Array.from(names).filter((n) => {
    if ((info.get(n)?.environments.length ?? 0) > 0) return false;
    return sourceUsed.has(n) || composeRefs.has(n) || exampleNames.has(n);
  });

  const sorted = Array.from(names).sort((a, b) => a.localeCompare(b));
  return { sorted, info, missing: missing.sort() };
}

function distinctEnvLabels(model: ProjectModel): string[] {
  const labels = new Set<string>();
  for (const file of model.envFiles) {
    if (file.environment && file.environment !== "example") labels.add(file.environment);
  }
  return Array.from(labels).sort();
}
