import type { ProjectModel } from "../models/project-model.js";

export interface ActionsChecklist {
  /** Names referenced via `${{ secrets.X }}`. */
  secrets: string[];
  /** Names referenced via `${{ vars.X }}`. */
  vars: string[];
}

/**
 * Collect the repository secrets and variables referenced by a project's
 * GitHub Actions workflows.
 */
export function collectActionsChecklist(model: ProjectModel): ActionsChecklist {
  const secrets = new Set<string>();
  const vars = new Set<string>();

  for (const file of model.actionFiles) {
    for (const usage of file.usages) {
      for (const origin of usage.origins) {
        if (origin.subkind === "vars") vars.add(usage.name);
        else if (origin.subkind === "secrets") secrets.add(usage.name);
      }
    }
  }

  const sorted = (set: Set<string>) => Array.from(set).sort((a, b) => a.localeCompare(b));
  return { secrets: sorted(secrets), vars: sorted(vars) };
}

/**
 * Generate `.github/ENVIRONMENT.md` — a checklist of the repository secrets
 * and variables that must be configured for the workflows to work. Names
 * only; values are never mentioned.
 */
export function generateActionsChecklist(model: ProjectModel): string {
  const { secrets, vars } = collectActionsChecklist(model);

  const lines: string[] = [];
  lines.push("# GitHub Actions environment checklist");
  lines.push("");
  lines.push("> Generated by envdoctor. Do not edit by hand.");
  lines.push("");
  lines.push(
    "Configure these repository secrets and variables (Settings → Secrets and variables → Actions).",
  );
  lines.push("");

  lines.push("## Secrets");
  if (secrets.length === 0) {
    lines.push("None.");
  } else {
    for (const name of secrets) lines.push(`- [ ] \`${name}\``);
  }
  lines.push("");

  lines.push("## Variables");
  if (vars.length === 0) {
    lines.push("None.");
  } else {
    for (const name of vars) lines.push(`- [ ] \`${name}\``);
  }
  lines.push("");

  return lines.join("\n");
}
