import fs from "node:fs";
import type { ProjectModel } from "../models/project-model.js";
import type { EnvdoctorConfig } from "../config/config.js";
import { inferType } from "../utils/type-infer.js";

type SchemaType = Record<string, Partial<NonNullable<EnvdoctorConfig["schema"]>[string]>>;

/**
 * Infer a validation schema for every known environment variable by inspecting
 * source-code usage patterns and existing env values.
 *
 * Examples:
 *   - parseInt(process.env.PORT)        → integer
 *   - Number(process.env.RATIO)         → float
 *   - process.env.DEBUG === "true"      → boolean
 *   - JSON.parse(process.env.CONFIG)    → json
 *   - process.env.API_URL               → string
 */
export function generateSchema(model: ProjectModel): string {
  const schema: SchemaType = {};

  // Infer from existing env values first.
  for (const file of model.envFiles) {
    for (const v of file.variables) {
      if (v.value === undefined) continue;
      const type = inferType(v.value);
      const mapped = mapInferredType(type);
      if (!mapped) continue;
      schema[v.name] = { type: mapped };
    }
  }

  // Refine from source usage patterns.
  for (const file of model.sourceFiles) {
    const content = fs.readFileSync(file.filePath, "utf8");
    const lines = content.split("\n");
    for (const usage of file.usages) {
      for (const origin of usage.origins) {
        if (origin.line === undefined) continue;
        const line = lines[origin.line - 1] ?? "";
        const inferred = inferFromLine(usage.name, line);
        if (!inferred) continue;
        schema[usage.name] = inferred;
      }
    }
  }

  const entries = Object.entries(schema).sort((a, b) => a[0].localeCompare(b[0]));
  if (entries.length === 0) {
    return `// Generated by envdoctor. No schema could be inferred.\nexport default {\n  schema: {},\n};\n`;
  }

  const lines: string[] = [];
  lines.push("// Generated by envdoctor. Merge into envdoctor.config.ts:");
  lines.push("// import schema from './envdoctor.schema'; export default { ..., ...schema };");
  lines.push("");
  lines.push("export default {");
  lines.push("  schema: {");
  for (const [name, spec] of entries) {
    const props: string[] = [];
    if (spec.type) props.push(`type: "${spec.type}"`);
    if (spec.optional) props.push("optional: true");
    if (spec.enum) props.push(`enum: [${spec.enum.map((s) => `"${s}"`).join(", ")}]`);
    if (spec.regex) props.push(`regex: "${spec.regex}"`);
    if (spec.min !== undefined) props.push(`min: ${spec.min}`);
    if (spec.max !== undefined) props.push(`max: ${spec.max}`);
    lines.push(`    ${name}: { ${props.join(", ")} },`);
  }
  lines.push("  },");
  lines.push("};");
  lines.push("");
  return lines.join("\n");
}

function mapInferredType(type: ReturnType<typeof inferType>): SchemaType[string]["type"] | null {
  switch (type) {
    case "integer":
    case "float":
    case "boolean":
    case "url":
    case "json":
      return type;
    case "string":
    default:
      return null;
  }
}

function inferFromLine(name: string, line: string): SchemaType[string] | null {
  const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const access = `process\\.env\\.${escaped}|import\\.meta\\.env\\.${escaped}`;

  if (new RegExp(`(parseInt|Number\\.parseInt)\\s*\\(\\s*(${access})`).test(line)) {
    return { type: "integer" };
  }
  if (
    new RegExp(
      `(Number\\s*\\(\\s*(${access})\\s*\\)|parseFloat|Number\\.parseFloat)\\s*\\(\\s*(${access})`,
    ).test(line)
  ) {
    return { type: "float" };
  }
  if (
    new RegExp(
      `(${access})\\s*===?\\s*["']true["']|(${access})\\s*===?\\s*["']false["']|Boolean\\s*\\(\\s*(${access})`,
    ).test(line)
  ) {
    return { type: "boolean" };
  }
  if (new RegExp(`JSON\\.parse\\s*\\(\\s*(${access})`).test(line)) {
    return { type: "json" };
  }

  return null;
}
