import { afterAll, beforeAll, describe, expect, it } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { runFix } from "../../src/commands/fix.js";
import { capture, copyFixtureToTemp } from "../helpers.js";

describe("envdoctor fix", () => {
  let tmpDir: string;

  beforeAll(() => {
    tmpDir = copyFixtureToTemp("sample-project");
  });

  afterAll(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  it("is non-destructive without --force", async () => {
    // The fixture already has a .env.example; ensure it is left untouched.
    const before = fs.readFileSync(path.join(tmpDir, ".env.example"), "utf8");
    const result = await capture(() =>
      runFix({ rootDir: tmpDir, dryRun: false, force: false, verbose: false }),
    );
    const after = fs.readFileSync(path.join(tmpDir, ".env.example"), "utf8");
    expect(before).toBe(after);
    expect(result.stdout).toContain("skipped .env.example");
  });

  it("creates ENVIRONMENT.md and the actions checklist", async () => {
    await capture(() => runFix({ rootDir: tmpDir, dryRun: false, force: true, verbose: false }));

    const doc = fs.readFileSync(path.join(tmpDir, "ENVIRONMENT.md"), "utf8");
    expect(doc).toContain("> Generated by envdoctor");

    const checklist = fs.readFileSync(path.join(tmpDir, ".github", "ENVIRONMENT.md"), "utf8");
    expect(checklist).toContain("- [ ] `DEPLOY_TOKEN`");
    expect(checklist).toContain("- [ ] `DATABASE_URL`");
  });

  it("never writes secret values into generated files", async () => {
    await capture(() => runFix({ rootDir: tmpDir, dryRun: false, force: true, verbose: false }));

    const envExample = fs.readFileSync(path.join(tmpDir, ".env.example"), "utf8");
    const doc = fs.readFileSync(path.join(tmpDir, "ENVIRONMENT.md"), "utf8");
    const checklist = fs.readFileSync(path.join(tmpDir, ".github", "ENVIRONMENT.md"), "utf8");
    const all = [envExample, doc, checklist].join("\n");

    expect(all).not.toContain("dev-key-123");
    expect(all).not.toContain("prod-only-secret");
    expect(all).not.toContain("stale-key");
    expect(all).not.toContain("redis://prod");
  });

  it("dry-run writes nothing", async () => {
    const untouched = path.join(tmpDir, "dry-run-project");
    fs.cpSync(path.join(tmpDir, "src"), path.join(untouched, "src"), { recursive: true });
    fs.writeFileSync(path.join(untouched, ".env"), "PORT=3000\n");

    const result = await capture(() =>
      runFix({ rootDir: untouched, dryRun: true, force: false, verbose: false }),
    );
    expect(result.stdout).toContain("dry run");
    expect(fs.existsSync(path.join(untouched, ".env.example"))).toBe(false);
    expect(fs.existsSync(path.join(untouched, "ENVIRONMENT.md"))).toBe(false);
  });
});
