import { describe, expect, it } from "vitest";
import { generateEnvironmentDoc } from "../../src/generators/environment-doc.js";
import { buildModel } from "../helpers.js";
import type { InMemoryFile } from "../helpers.js";

describe("generateEnvironmentDoc", () => {
  it("builds an overview table and per-environment sections", () => {
    const files: InMemoryFile[] = [
      { path: "/p/.env", content: "PORT=3000\nDEBUG=true\n" },
      { path: "/p/.env.production", content: "PORT=8080\n" },
      { path: "/p/src/index.ts", content: "const p = process.env.PORT;\n" },
    ];
    const out = generateEnvironmentDoc(buildModel(files));

    expect(out).toContain("> Generated by envdoctor");
    expect(out).toContain("| PORT | integer | development, production | ✓ | — |");
    expect(out).toContain("### development");
    expect(out).toContain("### production");
  });

  it("lists referenced-but-undefined variables", () => {
    const files: InMemoryFile[] = [
      { path: "/p/.env", content: "PORT=3000\n" },
      {
        path: "/p/src/index.ts",
        content: "const p = process.env.PORT;\nconst m = process.env.MYSTERY;\n",
      },
      { path: "/p/docker-compose.yml", content: "services:\n  api:\n    environment:\n      COMPOSE_ONLY: x\n" },
    ];
    const out = generateEnvironmentDoc(buildModel(files));

    expect(out).toContain("## Referenced but not defined");
    expect(out).toContain("`MYSTERY`");
    expect(out).toContain("`COMPOSE_ONLY`");
    expect(out).not.toContain("`PORT`");
  });

  it("marks secret-like variables in the table", () => {
    const files: InMemoryFile[] = [
      { path: "/p/.env", content: "API_KEY=abc\n" },
    ];
    const out = generateEnvironmentDoc(buildModel(files));
    expect(out).toContain("| API_KEY | string | development | — | ✓ |");
  });
});
