import { describe, expect, it } from "vitest";
import {
  collectActionsChecklist,
  generateActionsChecklist,
} from "../../src/generators/github-actions.js";
import { buildModel } from "../helpers.js";
import type { InMemoryFile } from "../helpers.js";

const WORKFLOW: InMemoryFile = {
  path: "/p/.github/workflows/ci.yml",
  content:
    "name: ci\non: [push]\njobs:\n  t:\n    runs-on: ubuntu-latest\n    steps:\n      - run: echo ${{ secrets.DEPLOY_TOKEN }} ${{ vars.REGION }}\n",
};

describe("collectActionsChecklist", () => {
  it("separates secrets from vars", () => {
    const checklist = collectActionsChecklist(buildModel([WORKFLOW]));
    expect(checklist.secrets).toEqual(["DEPLOY_TOKEN"]);
    expect(checklist.vars).toEqual(["REGION"]);
  });

  it("returns empty lists when there are no workflows", () => {
    const checklist = collectActionsChecklist(buildModel([]));
    expect(checklist.secrets).toEqual([]);
    expect(checklist.vars).toEqual([]);
  });
});

describe("generateActionsChecklist", () => {
  it("renders checkbox lists and never mentions values", () => {
    const out = generateActionsChecklist(buildModel([WORKFLOW]));
    expect(out).toContain("> Generated by envdoctor");
    expect(out).toContain("- [ ] `DEPLOY_TOKEN`");
    expect(out).toContain("- [ ] `REGION`");
    expect(out).toContain("## Variables");
  });
});
